name: Create Release

on: workflow_dispatch

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build mod jar
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      - name: Create release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/${{ github.event.repository.name }}.jar
          tag: ${{ github.run_number }}